// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary model header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef VERILATED_VSAURIA_TESTER_H_
#define VERILATED_VSAURIA_TESTER_H_  // guard

#include "verilated.h"
#include "verilated_save.h"

class Vsauria_tester__Syms;
class Vsauria_tester___024root;
class VerilatedVcdC;
class Vsauria_tester_AXI_BUS__A20_AB80_AC4;
class Vsauria_tester_AXI_BUS__A20_AB80_AC4_AD1;
class Vsauria_tester_axi_lite_mux__pi15;
class Vsauria_tester_AXI4Lite__W20_A20;
class Vsauria_tester_FIFO_READ__D80;
class Vsauria_tester_FIFO_WRITE__D80;
class Vsauria_tester_feed_xy_lane__F5_W3;
class Vsauria_tester_feed_xy_lane__pi45;
class Vsauria_tester_sa_processing_element__pi48;


// This class is the main interface to the Verilated model
class Vsauria_tester VL_NOT_FINAL {
  private:
    // Symbol table holding complete model state (owned by this class)
    Vsauria_tester__Syms* const vlSymsp;

  public:

    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(&rstn_sauria,0,0);
    VL_IN8(&clk_sauria,0,0);
    VL_IN8(&rstn_sys,0,0);
    VL_IN8(&clk_sys,0,0);
    VL_IN8(&check_flag,0,0);
    VL_IN8(&file_opts,1,0);
    VL_IN8(&cfg_bus_lite_ar_valid,0,0);
    VL_OUT8(&cfg_bus_lite_ar_ready,0,0);
    VL_OUT8(&cfg_bus_lite_r_valid,0,0);
    VL_IN8(&cfg_bus_lite_r_ready,0,0);
    VL_IN8(&cfg_bus_lite_aw_valid,0,0);
    VL_OUT8(&cfg_bus_lite_aw_ready,0,0);
    VL_IN8(&cfg_bus_lite_w_valid,0,0);
    VL_OUT8(&cfg_bus_lite_w_ready,0,0);
    VL_IN8(&test_idx,7,0);
    VL_OUT8(&ctrl_interrupt,0,0);
    VL_OUT8(&sauria_interrupt,0,0);
    VL_OUT8(&dma_interrupt,0,0);
    VL_IN(&cfg_bus_lite_ar_addr,31,0);
    VL_OUT(&cfg_bus_lite_r_data,31,0);
    VL_IN(&cfg_bus_lite_aw_addr,31,0);
    VL_IN(&cfg_bus_lite_w_data,31,0);
    VL_IN(&dram_startoffs,31,0);
    VL_IN(&dram_endoffs,31,0);
    VL_OUT(&errors,31,0);

    // CELLS
    // Public to allow access to /* verilator public */ items.
    // Otherwise the application code can consider these internals.
    Vsauria_tester_AXI_BUS__A20_AB80_AC4* const __PVT__sauria_tester__DOT__dat_bus;
    Vsauria_tester_AXI_BUS__A20_AB80_AC4_AD1* const __PVT__sauria_tester__DOT__dut__DOT__io_mem_port;
    Vsauria_tester_AXI_BUS__A20_AB80_AC4_AD1* const __PVT__sauria_tester__DOT__dut__DOT__dma_mem_sauria;
    Vsauria_tester_AXI_BUS__A20_AB80_AC4_AD1* const __PVT__sauria_tester__DOT__dut__DOT__debug_mem_sauria;
    Vsauria_tester_AXI_BUS__A20_AB80_AC4_AD1* const __PVT__sauria_tester__DOT__dut__DOT__core_mem_mux__BRA__1__KET__;
    Vsauria_tester_AXI_BUS__A20_AB80_AC4_AD1* const __PVT__sauria_tester__DOT__dut__DOT__core_mem_mux__BRA__0__KET__;
    Vsauria_tester_axi_lite_mux__pi15* const __PVT__sauria_tester__DOT__dut__DOT__core_cfg_mux_i__DOT__i_axi_mux;
    Vsauria_tester_axi_lite_mux__pi15* const __PVT__sauria_tester__DOT__dut__DOT__dma_cfg_mux_i__DOT__i_axi_mux;
    Vsauria_tester_AXI4Lite__W20_A20* const __PVT__sauria_tester__DOT__dut__DOT__df_controller_i__DOT__config_axilite;
    Vsauria_tester_AXI4Lite__W20_A20* const __PVT__sauria_tester__DOT__dut__DOT__df_controller_i__DOT__sauria_axilite;
    Vsauria_tester_AXI4Lite__W20_A20* const __PVT__sauria_tester__DOT__dut__DOT__df_controller_i__DOT__dma_axilite;
    Vsauria_tester_FIFO_READ__D80* const __PVT__sauria_tester__DOT__dut__DOT__dma_top_i__DOT__dma_i__DOT__reader_fifo_read;
    Vsauria_tester_FIFO_WRITE__D80* const __PVT__sauria_tester__DOT__dut__DOT__dma_top_i__DOT__dma_i__DOT__reader_fifo_write;
    Vsauria_tester_FIFO_READ__D80* const __PVT__sauria_tester__DOT__dut__DOT__dma_top_i__DOT__dma_i__DOT__writer_fifo_read;
    Vsauria_tester_FIFO_WRITE__D80* const __PVT__sauria_tester__DOT__dut__DOT__dma_top_i__DOT__dma_i__DOT__writer_fifo_write;
    Vsauria_tester_feed_xy_lane__F5_W3* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__0__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__1__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__2__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__3__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__4__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__5__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__6__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__7__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__0__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__1__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__2__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__3__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__4__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__5__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__6__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__7__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__8__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__9__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__10__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__11__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__12__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__13__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__14__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__15__KET____DOT__act_row_feeder_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48* const __PVT__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;

    // Root instance pointer to allow access to model internals,
    // including inlined /* verilator public_flat_* */ items.
    Vsauria_tester___024root* const rootp;

    // CONSTRUCTORS
    /// Construct the model; called by application code
    /// If contextp is null, then the model will use the default global context
    /// If name is "", then makes a wrapper with a
    /// single model invisible with respect to DPI scope names.
    explicit Vsauria_tester(VerilatedContext* contextp, const char* name = "TOP");
    explicit Vsauria_tester(const char* name = "TOP");
    /// Destroy the model; called (often implicitly) by application code
    virtual ~Vsauria_tester();
  private:
    VL_UNCOPYABLE(Vsauria_tester);  ///< Copying not allowed

  public:
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    /// Trace signals in the model; called by application code
    void trace(VerilatedVcdC* tfp, int levels, int options = 0);
    /// Return current simulation context for this model.
    /// Used to get to e.g. simulation time via contextp()->time()
    VerilatedContext* contextp() const;
    /// Retrieve name of this model instance (as passed to constructor).
    const char* name() const;

    // Serialization functions
    friend VerilatedSerialize& operator<<(VerilatedSerialize& os, Vsauria_tester& rhs);
    friend VerilatedDeserialize& operator>>(VerilatedDeserialize& os, Vsauria_tester& rhs);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

#endif  // guard
