// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VSAURIA_TESTER__SYMS_H_
#define VERILATED_VSAURIA_TESTER__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "Vsauria_tester.h"

// INCLUDE MODULE CLASSES
#include "Vsauria_tester___024root.h"
#include "Vsauria_tester_AXI_BUS__A20_AB80_AC4.h"
#include "Vsauria_tester_AXI_BUS__A20_AB80_AC4_AD1.h"
#include "Vsauria_tester_axi_lite_mux__pi15.h"
#include "Vsauria_tester_AXI4Lite__W20_A20.h"
#include "Vsauria_tester_FIFO_READ__D80.h"
#include "Vsauria_tester_FIFO_WRITE__D80.h"
#include "Vsauria_tester_feed_xy_lane__F5_W3.h"
#include "Vsauria_tester_feed_xy_lane__pi45.h"
#include "Vsauria_tester_sa_processing_element__pi48.h"

// SYMS CLASS (contains all model state)
class Vsauria_tester__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vsauria_tester* const __Vm_modelp;
    bool __Vm_activity = false;  ///< Used by trace routines to determine change occurred
    uint32_t __Vm_baseCode = 0;  ///< Used by trace routines when tracing multiple models
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vsauria_tester___024root       TOP;
    Vsauria_tester_AXI_BUS__A20_AB80_AC4 TOP__sauria_tester__DOT__dat_bus;
    Vsauria_tester_axi_lite_mux__pi15 TOP__sauria_tester__DOT__dut__DOT__core_cfg_mux_i__DOT__i_axi_mux;
    Vsauria_tester_AXI4Lite__W20_A20 TOP__sauria_tester__DOT__dut__DOT__df_controller_i__DOT__sauria_axilite;
    Vsauria_tester_axi_lite_mux__pi15 TOP__sauria_tester__DOT__dut__DOT__dma_cfg_mux_i__DOT__i_axi_mux;
    Vsauria_tester_FIFO_READ__D80  TOP__sauria_tester__DOT__dut__DOT__dma_top_i__DOT__dma_i__DOT__reader_fifo_read;
    Vsauria_tester_FIFO_WRITE__D80 TOP__sauria_tester__DOT__dut__DOT__dma_top_i__DOT__dma_i__DOT__reader_fifo_write;
    Vsauria_tester_FIFO_READ__D80  TOP__sauria_tester__DOT__dut__DOT__dma_top_i__DOT__dma_i__DOT__writer_fifo_read;
    Vsauria_tester_FIFO_WRITE__D80 TOP__sauria_tester__DOT__dut__DOT__dma_top_i__DOT__dma_i__DOT__writer_fifo_write;
    Vsauria_tester_AXI_BUS__A20_AB80_AC4_AD1 TOP__sauria_tester__DOT__dut__DOT__io_mem_port;
    Vsauria_tester_feed_xy_lane__F5_W3 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__0__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__1__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__2__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__3__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__4__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__5__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__6__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_feed_xy_lane__F5_W3 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__ifmap_feeder_i__DOT__y_axis__BRA__7__KET____DOT__ifmap_feeder_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__0__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__1__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__2__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__3__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__4__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__5__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__6__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__0__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__10__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__11__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__12__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__13__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__14__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__15__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__1__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__2__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__3__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__4__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__5__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__6__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__7__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__8__KET____DOT__sa_processing_element_i;
    Vsauria_tester_sa_processing_element__pi48 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__sa_array_i__DOT__y_axis__BRA__7__KET____DOT__x_axis__BRA__9__KET____DOT__sa_processing_element_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__0__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__10__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__11__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__12__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__13__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__14__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__15__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__1__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__2__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__3__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__4__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__5__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__6__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__7__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__8__KET____DOT__act_row_feeder_i;
    Vsauria_tester_feed_xy_lane__pi45 TOP__sauria_tester__DOT__dut__DOT__sauria_core_i__DOT__sauria_logic_top_i__DOT__weight_feeder_i__DOT__x_axis__BRA__9__KET____DOT__act_row_feeder_i;

    // CONSTRUCTORS
    Vsauria_tester__Syms(VerilatedContext* contextp, const char* namep, Vsauria_tester* modelp);
    ~Vsauria_tester__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
    void __Vserialize(VerilatedSerialize& os);
    void __Vdeserialize(VerilatedDeserialize& os);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

#endif  // guard
